
export const ADDAPPOINTMENT = "ADDAPPOINTMENT";
export const ACCEPTAPPOINTMENT = "ACCEPTAPPOINTMENT";
export const UPDATEAPPOINTMENT = "UPDATEAPPOINTMENT";
export const DELETEREQUEST = "DELETEREQUEST"